### ISSUE TITLE
Certificate parsing error in 0.21.0-alpha.1

### ISSUE THREAD

**Issue by mgdm** [rustls/rustls#1246]
Hi,
I've been using rustls with rustls-native-certs and loading the certificates from the system keychain on macOS Ventura. This works fine with v0.20.8, but when I moved to the alpha it fails to parse at least one of the certificates in the system keychain. Using the system store works fine on Linux.

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidByte(64, 10)', src/main.rs:31:48
```

I've created an example that reproduces the issue either with the system keychain or with the specific certificate at https://github.com/mgdm/rustls-parsing-crash.

**Comment by jsha** [comment]
Thanks for the excellent bug report, along with the useful example.

At a first glance, I suspect what's needed is [RootCertStore::add_parseable_certificates](https://docs.rs/rustls/latest/rustls/struct.RootCertStore.html#method.add_parsable_certificates):

> Parse the given DER-encoded certificates and add all that can be parsed in a best-effort fashion.
> This is because large collections of root certificates often include ancient or syntactically invalid certificates.
> Returns the number of certificates added, and the number that were ignored.

We should definitely do a better job of signposting that function from rustls-native-certs and in rustls, though.

**Comment by cpu** [comment]
> I've created an example that reproduces the issue either with the system keychain or with the specific certificate at https://github.com/mgdm/rustls-parsing-crash.

I don't have a MacOS machine handy to try the `cargo run system` reproducer option, but I do notice when I run `cargo run` for the embedded variant that the panic happening from unwrapping an error result from the `b64.decode` call. E.g. it happens _before_ Rustls is in the mix.

Is it possible the embedded cert's b64 DER content was mis-pasted into the repro?

**Comment by cpu** [comment]
> At a first glance, I suspect what's needed is [RootCertStore::add_parseable_certificates](https://docs.rs/rustls/latest/rustls/struct.RootCertStore.html#method.add_parsable_certificates):

That seems to do the trick for me :tada: 

https://github.com/cpu/rustls-parsing-crash/commit/6d55785e972a417c18acf12da53dfda530c5ff7c

I used `rustls_pemfile` for convenience but the crux of the fix is using `add_parseable_certificates`.

**Comment by mgdm** [comment]
That's certainly neater and I'll switch to that, thanks!

I'm still curious about why, now that I've fixed the base64 issue, that certificate appears to parse under 0.20.8 and not under 0.21.0-alpha.1? Hopefully you can follow this shell session, where I do `cargo run` with 0.20.8 which appears to work, and then edit Cargo.toml to switch to the 0.21.0-alpha.1 and try again, and observe a parsing error. This is testing the embedded, fixed version of the cert, but the same thing happens with the system truststore. 

```console
michael@Michaels-MBP rustls-parsing-crash % cargo run
   Compiling cc v1.0.79
   Compiling core-foundation-sys v0.8.3
   Compiling libc v0.2.140
   Compiling untrusted v0.7.1
   Compiling log v0.4.17
   Compiling base64 v0.21.0
   Compiling cfg-if v1.0.0
   Compiling rustls v0.20.8
   Compiling bitflags v1.3.2
   Compiling rustls-pemfile v1.0.2
   Compiling ring v0.16.20
   Compiling security-framework-sys v2.8.0
   Compiling core-foundation v0.9.3
   Compiling security-framework v2.8.2
   Compiling rustls-native-certs v0.6.2
   Compiling sct v0.7.0
   Compiling webpki v0.22.0
   Compiling rustls-test v0.1.0 (/Users/michael/Code/Upstream/rustls-parsing-crash)
    Finished dev [unoptimized + debuginfo] target(s) in 3.92s
     Running `target/debug/rustls-test`
michael@Michaels-MBP rustls-parsing-crash % vim Cargo.toml
michael@Michaels-MBP rustls-parsing-crash % cargo clean
michael@Michaels-MBP rustls-parsing-crash % cargo run
    Updating crates.io index
   Compiling cc v1.0.79
   Compiling libc v0.2.140
   Compiling core-foundation-sys v0.8.3
   Compiling untrusted v0.7.1
   Compiling log v0.4.17
   Compiling base64 v0.21.0
   Compiling cfg-if v1.0.0
   Compiling bitflags v1.3.2
   Compiling rustls v0.21.0-alpha.1
   Compiling rustls-pemfile v1.0.2
   Compiling ring v0.16.20
   Compiling security-framework-sys v2.8.0
   Compiling core-foundation v0.9.3
   Compiling security-framework v2.8.2
   Compiling rustls-native-certs v0.6.2
   Compiling sct v0.7.0
   Compiling rustls-webpki v0.100.0
   Compiling rustls-test v0.1.0 (/Users/michael/Code/Upstream/rustls-parsing-crash)
    Finished dev [unoptimized + debuginfo] target(s) in 4.99s
     Running `target/debug/rustls-test`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidCertificate(BadEncoding)', src/main.rs:13:48
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1112:23
   4: rustls_test::main
             at ./src/main.rs:13:27
   5: core::ops::function::FnOnce::call_once
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
michael@Michaels-MBP rustls-parsing-crash %
```

**Comment by cpu** [comment]
> I'm still curious about why, now that I've fixed the base64 issue, that certificate appears to parse under 0.20.8 and not under 0.21.0-alpha.1?

That's a good question. I'm not sure of an answer off-hand but I suspect it has to do with rustls 0.21.0-alpha.1 switching to a forked [rustls/webpki](https://github.com/rustls/webpki) crate that [rolled in many updates](https://github.com/briansmith/webpki/compare/main...rustls:webpki:main). You might have luck trying to bisect there.

**Comment by cpu** [comment]
> I suspect it has to do with rustls 0.21.0-alpha.1 switching to a forked [rustls/webpki](https://github.com/rustls/webpki) crate that [rolled in many updates](https://github.com/briansmith/webpki/compare/main...rustls:webpki:main).

I notice linters complaining about this certificate's serial length (https://crt.sh/?id=8566260&opt=zlint,cablint). We touched that part of webpki recently: https://github.com/rustls/webpki/pull/36

**Comment by cpu** [comment]
(Sorry about the in/out commenting, poking at this between CI runs :sweat_smile:)

> In particular I had https://github.com/rustls/webpki/pull/36#discussion_r1134246176 a change where I thought the previous upstream webpki check was overly permissive.

Looking at the [ASN.1 decoding of this cert](https://lapo.it/asn1js/#MIIDcTCCAlmgAwIBAgIVAOYJ_nrqAGiM4CS07SAbH-9StETRMA0GCSqGSIb3DQEBBQUAMFAxCzAJBgNVBAYTAlBMMSgwJgYDVQQKDB9LcmFqb3dhIEl6YmEgUm96bGljemVuaW93YSBTLkEuMRcwFQYDVQQDDA5TWkFGSVIgUk9PVCBDQTAeFw0xMTEyMDYxMTEwNTdaFw0zMTEyMDYxMTEwNTdaMFAxCzAJBgNVBAYTAlBMMSgwJgYDVQQKDB9LcmFqb3dhIEl6YmEgUm96bGljemVuaW93YSBTLkEuMRcwFQYDVQQDDA5TWkFGSVIgUk9PVCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKxHL49ZMTml6g3wpYwrvQKkvc0Kc6oJ5sxfgmp1qZfluwbv88BdocHSiXlY8NzrVYzuWBp7J_9KULMAoWoTIzOQ6C9TNm4YbA9A1jdX1wYNL5Akylf8W5L_I4BXhT9KnlI6x-a7BVAmnr_Ttl-utT_Asms2fRfEsF2vZPMxH4UFqOAhFjxTkmJWf2Cu4nvRQJHcttB-cEAoag_hERt_-tzo4URz6x6r19toYmxx4FjjBkUhWQw1X21re__Hof2-0YgiwYT84zLbeqDqCOMOXxvH480yGDkh_QoazWX3U75HQExT_iJlwnu7I1V6HXztKIwCBjsxffbH3jOshCJtywcCAwEAAaNCMEAwDwYDVR0TAQH_BAUwAwEB_zAOBgNVHQ8BAf8EBAMCAQYwHQYDVR0OBBYEFFOSo33_gnbwM9TrkmdHYTMbaDsqMA0GCSqGSIb3DQEBBQUAA4IBAQA5UFWd5EL_pBviIMm1zD2JLUCpp0mJG7JkwznIOzawhGmFFaxGoxAhQBEghaP-E0KR66oAwVC6xe32QUVSHfWqWndzbODzLB8yj7WAR0cDM45ZngSBPBuFE3WuGLJX9g100ETfIX-4YBR_4NR_uvTnpnd9ete7Whl0ZfY94yuu4xQqB5QFv-P7IXXVlTOjkjuGXEcyQAjQzbFaT9vIABSbeCXWBbjvOXukJy6WgAiclzGNSYprre8RyyddfmjW9HIGwsIO03EldivvqEYL1Hv1w_Pur-6FUEOaL68PEIUovfgwIB2BAw-vZDuwcH0mX548PojGyg434cDjkSXa3mHF) the encoded serial number fits into the exact circumstance mentioned in my [comment](https://github.com/rustls/webpki/pull/36#discussion_r1134246176). With the leading `00` required for a positive integer we get a 21 octet serial number in DER encoding, which violates [RFC 5280's requirement](https://www.rfc-editor.org/rfc/rfc5280#section-4.1.2.2) of 20 octet serial numbers: `00 E6 09 FE 7A EA 00 68 8C  E0 24 B4 ED 20 1B 1F EF 52 B4 44 D1`.

Prior versions of webpki allowed this malformed certificate to parse because it incorrectly checked the length of the serial [after removing the leading `00`](https://github.com/briansmith/webpki/blob/b481381e914de604df30b1be2fe72d938a5c0e57/src/cert.rs#L156) whereas the updated webpki used by rustls 0.21.0-alpha.1 [checks the overall length including the leading 00](https://github.com/rustls/webpki/blob/498014f4754d7328ab2e2e6c6ce4729db6ff360b/src/cert.rs#L151-L152).

That should explain the change in behaviour. I think we just need to figure out the best way to point users towards the permissive function for loading this problematic root.

**Comment by mgdm** [comment]
Thank you for looking into that for me! I didn't have quite enough knowledge of the certificate structure to be able to diagnose that. I'll move my code to [RootCertStore::add_parseable_certificates](https://docs.rs/rustls/latest/rustls/struct.RootCertStore.html#method.add_parsable_certificates) which solves my problem. I had a look at [the Mozilla included CAs](https://ccadb.my.salesforce-sites.com/mozilla/IncludedCACertificateReport) and noticed that one isn't on the list, though another called `SZAFIR ROOT CA2` is, so it'll be safe to ignore.

**Comment by cpu** [comment]
I put up a couple small PRs to try and improve our docs:
* for rustls, https://github.com/rustls/rustls/pull/1248
* for rustls-native-certs: https://github.com/rustls/rustls-native-certs/pull/62
