### ISSUE TITLE
rustls::Stream not working on some domains with rustls 0.21.7

### ISSUE THREAD

**Issue by darind** [rustls/rustls#1452]
I am trying to use `rustls::Stream` to perform a client HTTPS request but it doesn't seem to be working with some domains.

`Cargo.toml`:

```
[package]
name = "rust-client-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rustls = "0.21.7"
webpki-roots = "0.25.2"
```

`main.rs` (taken from https://github.com/rustls/rustls/blob/v/0.21.7/examples/src/bin/simpleclient.rs):

```
use std::sync::Arc;

use std::io::{stdout, Read, Write};
use std::net::TcpStream;

use rustls::{OwnedTrustAnchor, RootCertStore};

fn main() {
    let mut root_store = RootCertStore::empty();
    root_store.add_trust_anchors(webpki_roots::TLS_SERVER_ROOTS.iter().map(|ta| {
        OwnedTrustAnchor::from_subject_spki_name_constraints(
            ta.subject,
            ta.spki,
            ta.name_constraints,
        )
    }));
    let config = rustls::ClientConfig::builder()
        .with_safe_defaults()
        .with_root_certificates(root_store)
        .with_no_client_auth();

    let server_name = "www.google.com".try_into().unwrap();
    let mut conn = rustls::ClientConnection::new(Arc::new(config), server_name).unwrap();
    let mut sock = TcpStream::connect("www.google.com:443").unwrap();
    let mut tls = rustls::Stream::new(&mut conn, &mut sock);
    tls.write_all(
        concat!(
            "GET / HTTP/1.1\r\n",
            "Host: www.google.com\r\n",
            "Connection: close\r\n",
            "\r\n"
        )
        .as_bytes(),
    )
    .unwrap();
    let ciphersuite = tls
        .conn
        .negotiated_cipher_suite()
        .unwrap();
    writeln!(
        &mut std::io::stderr(),
        "Current ciphersuite: {:?}",
        ciphersuite.suite()
    )
    .unwrap();
    let mut plaintext = Vec::new();
    tls.read_to_end(&mut plaintext).unwrap();
    stdout().write_all(&plaintext).unwrap();
}
```

I am getting the following error if I test with `www.google.com`:

```
Current ciphersuite: TLS13_AES_256_GCM_SHA384
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Kind(UnexpectedEof)', src/main.rs:47:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1107:23
   4: rust_client_test::main
             at ./src/main.rs:47:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

If I replace `www.google.com` with `example.com` or some other domain, then it works.

I also tried using an older version of rustls (0.17.0) and it worked without problems.

**Comment by djc** [comment]
See for more context #1299 and #1188 and #1327. The upshot I think might be that if you're satisfied that the HTTP response is complete (for example, if you get a `Content-Length` header and the appropriate amount of body bytes), you can just ignore this error.

@davidben any chance Google will start sending CloseNotify messages from the server?
