### ISSUE TITLE
Do we do the right thing when there's data after a `close_notify` alert?

### ISSUE THREAD

**Issue by briansmith** [rustls/rustls#959]
I was reading the code and was struck by this:

```rust
    pub fn reader(&mut self) -> Reader {
        Reader {
            received_plaintext: &mut self.common_state.received_plaintext,
            /// Are we done? i.e., have we processed all received messages, and received a
            /// close_notify to indicate that no new messages will arrive?
            peer_cleanly_closed: self
                .common_state
                .has_received_close_notify
                && !self.message_deframer.has_pending(),
            has_seen_eof: self.common_state.has_seen_eof,
        }
    }
```

Consider the unusual case where we receive in the same TCP packet a valid close_notify Alert followed by an ApplicationData record. Then `has_received_close_notify` will be true but `self.message_deframer.has_pending()` may be true. Then `peer_cleanly_closed` will be false, right?

Now consider this logic later:
```
            match (self.peer_cleanly_closed, self.has_seen_eof) {
                // cleanly closed; don't care about TCP EOF: express this as Ok(0)
                (true, _) => {}
                // unclean closure
                (false, true) => return Err(io::ErrorKind::UnexpectedEof.into()),
                // connection still going, but need more data: signal `WouldBlock` so that
                // the caller knows this
                (false, false) => return Err(io::ErrorKind::WouldBlock.into()),
            }
```

My thinking is that we may hit the `(false, false)` case and return `Err(io::ErrorKind::WouldBlock.into())`. Is that true?

If so, I am not sure that `Err(io::ErrorKind::WouldBlock.into())` would be the right thing to return. I think instead when we receive a `close_notify` alert then we should discard any remaining already-read data after the alert and ensure we never try to read any more (act like we've seen EOF). And, in particular, we should ensure that any subsequent attempt to read data will return EOF instead of returning any data after close_notify.

We should document that it is possible that there might have been data received that wasn't processed after the close_notify, and give advice on what the application should do.

Regardless, I think instead of combining `has_received_close_notify && !self.message_deframer.has_pending()` into a single `peer_cleanly_closed` variable, it would be clearer to instead have the match above handle the triple `(has_received_close_notify, deframer_has_pending, has_seen_eof)`.

If everything is the way we want it to be, then at the very least we should add some comments to explain this.

**Comment by briansmith** [comment]
In particular, the public documentation has a different definition of a "clean close":

```
    /// If the peer closes the TLS session cleanly, this returns `Ok(0)`  once all
    /// the pending data has been read. No further data can be received on that
    /// connection, so the underlying TCP connection should be half-closed too.
    ///
    /// If the peer closes the TLS session uncleanly (a TCP EOF without sending a
    /// `close_notify` alert) this function returns `Err(ErrorKind::UnexpectedEof.into())`
    /// once any pending data has been read.
```

In the description in the public documentation, we seem to consider a "clean close" to be one where there is a close_notify followed by EOF, but we don't consider what happens if there's anything in betweek.

**Comment by briansmith** [comment]
The TLS 1.3 spec says: " Any data received after a closure alert has been received MUST be ignored."

**Comment by djc** [comment]
I mainly touched it by moving things around IIRC, I think @ctz did the I/O changes for 0.20.

**Comment by briansmith** [comment]
As I mentioned in #989, I think the best way to model this is by introducing a new `CloseNotifyReceived` state that `ExpectTraffic` transitions to when we receive a `close_notify` alert.

**Comment by djc** [comment]
@ctz, hmm, is this related to #1905?

**Comment by schreter** [comment]
I hit the problem today, sending some plaintext data after close notify. If there is some data past the close notify received in the same buffer as the close notify (i.e., we are putting some garbage past TLS data into `UnbufferedConnectionCommon::process_tls_records_common()`), then the deframer panics like this:

```
thread 'tls_stream::tests::test_zc_zc' panicked at /Users/d039184/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/common_state.rs:564:9:
assertion failed: !self.sent_fatal_alert
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::panicking::panic
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:145:5
   3: rustls::common_state::CommonState::send_fatal_alert
             at /Users/d039184/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/common_state.rs:564:9
   4: rustls::conn::ConnectionCore<Data>::handle_deframe_error
             at /Users/d039184/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/conn.rs:1095:21
   5: rustls::conn::ConnectionCore<Data>::process_more_input
             at /Users/d039184/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/conn.rs:968:44
   6: rustls::conn::ConnectionCore<Data>::deframe
             at /Users/d039184/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/conn.rs:930:13
   7: rustls::conn::unbuffered::<impl rustls::conn::UnbufferedConnectionCommon<Data>>::process_tls_records_common
             at /Users/d039184/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/conn/unbuffered.rs:84:23
   8: rustls::conn::unbuffered::<impl rustls::conn::UnbufferedConnectionCommon<rustls::server::server_conn::ServerConnectionData>>::process_tls_records
             at /Users/d039184/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/rustls-0.23.27/src/conn/unbuffered.rs:33:9
```

As per the spec, the remainder of the buffer should be ignored, but it isn't. So yes, there is a bug.

IMHO, if `has_received_close_notify` is set, then we can't call `deframe()` anymore, since it works on garbage and `deframer_output` must be set to `None`.

@ctz From the discussion above, you seem to be working on these parts. Maybe something as simple as changing:

```rust
            let deframer_output =
                match self
                    .core
                    .deframe(None, buffer.filled_mut(), &mut buffer_progress) { ... }
```

to

```rust
            let deframer_output = if self.core.common_state.has_received_close_notify { None } else {
                match self
                    .core
                    .deframe(None, buffer.filled_mut(), &mut buffer_progress) { ... }
            }
```

would do the trick?

**Comment by ctz** [comment]
Hi @schreter thanks for the follow-up. Could you look at our existing test for this case at https://github.com/rustls/rustls/blob/87f37dd44e32b2771fa471a5d8111749ca9e7aa7/rustls/tests/unbuffered.rs#L548 and try and determine how your repro case differs, and file a PR that adds a failing test for it?

**Comment by schreter** [comment]
Hi @ctz,

I modified the test as follows:

```rust
diff --git a/rustls/tests/unbuffered.rs b/rustls/tests/unbuffered.rs
index 3942e2fd..b34c79c8 100644
--- a/rustls/tests/unbuffered.rs
+++ b/rustls/tests/unbuffered.rs
@@ -560,8 +560,8 @@ fn junk_after_close_notify_received() {
         .unwrap()
     );
 
-    client_send_buf[len..len + 4].copy_from_slice(&[0x17, 0x03, 0x03, 0x01]);
-    len += 4;
+    client_send_buf[len..len + 15].copy_from_slice(&[11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]);
+    len += 15;
 
     let discard = match dbg!(server.process_tls_records(dbg!(&mut client_send_buf[..len]))) {
         UnbufferedStatus {
```

This is in fact my test case in our project - adding exactly those 15 bytes.

This makes the test fail with:

```
[rustls/tests/runners/./../unbuffered.rs:566:25] server.process_tls_records(dbg!(&mut client_send_buf[..len])) = UnbufferedStatus {
    discard: 24,
    state: Err(
        InvalidMessage(
            InvalidContentType,
        ),
    ),
}

thread 'tests_with_aws_lc_rs::tests::junk_after_close_notify_received' panicked at rustls/tests/runners/./../unbuffered.rs:576:13:
unexpected server state UnbufferedStatus { discard: 24, state: Err(InvalidMessage(InvalidContentType)) } (wanted PeerClosed)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I.e., there seems to be some problem.

I suppose, the test has simply too few bytes (4 extra bytes) or the bytes seem to be a valid TLS record, whatever. With other, longer pattern, the test fails.

And yes, the minimal change I proposed above does fix the issue. I.e., with this:

```rust
diff --git a/rustls/src/conn/unbuffered.rs b/rustls/src/conn/unbuffered.rs
index 99d95e9e..e7794515 100644
--- a/rustls/src/conn/unbuffered.rs
+++ b/rustls/src/conn/unbuffered.rs
@@ -80,7 +80,7 @@ impl<Data> UnbufferedConnectionCommon<Data> {
                 );
             }
 
-            let deframer_output =
+            let deframer_output = if self.core.common_state.has_received_close_notify { None } else {
                 match self
                     .core
                     .deframe(None, buffer.filled_mut(), &mut buffer_progress)
@@ -93,7 +93,8 @@ impl<Data> UnbufferedConnectionCommon<Data> {
                         };
                     }
                     Ok(r) => r,
-                };
+                }
+            };
 
             if let Some(msg) = deframer_output {
                 let mut state =
```

the issue is gone, even with modified test.

**Comment by djc** [comment]
@schreter sounds good, can you submit a PR with the fix and the added test?

**Comment by briansmith** [comment]
> As I mentioned in [#989](https://github.com/rustls/rustls/issues/989), I think the best way to model this is by introducing a new `CloseNotifyReceived` state that `ExpectTraffic` transitions to when we receive a `close_notify` alert.

I still think the above is the best way to solve this problem. The root cause of this and other state machine bugs is that the state machine is only partly modeled by the enum, while many aspects of the state are handled in an ad-hoc fashion. IDK how we're going to ever become confident in the code without replacing the ad-hoc handling.

**Comment by schreter** [comment]
> I still think the above is the best way to solve this problem.

@briansmith I agree, but that's way beyond my current capa I can put in the project.

@djc I'll make a small PR to fix the bug with the oneliner and adjust the test to test both cases (the one that went through previously and the new one). Probably later today or on the weekend.

**Comment by ctz** [comment]
The idea of handling alerts in the state machine I think is a good one, but beware that the state machine operates on a sequence of whole TLS messages, so it has a limited effect on layers above that (and whether to read data at all is _several_ layers above that).

The other thing to note here is that every state in every state machine would need to handle alerts in exactly the same way; that commonality is why it doesn't currently happen in this way. But that is nothing some additional layering (eg, make `State::handle` concrete and handle alerts, before passing off to the state-specific code) couldn't address.
